id = "c3"
name = "C3"
version = "0.0.3"
schema_version = 1
authors = ["Aiden Olsen <olsenaiden33@gmail.com>"]
description = "This extension bring basic c3 language support to zed. NOTE: This extension is still a WIP!"
repository = "https://github.com/AineeJames/c3-zed"

[language_servers.c3]
name = "c3"
language = "C3"

[grammars.c3]
repository = "https://github.com/c3lang/tree-sitter-c3"
rev = "7d5474b5038a6f890b0649457c04db0f57f642fc"
