name = "C3"
grammar = "c3"
path_suffixes = ["c3", "c3i"]
autoclose_before = ";:.,=}])>"
line_comments = ["// "]
brackets = [
    { start = "(", end = ")", close = true, newline = true },
    { start = "(<", end = ">", close = true, newline = true },
    { start = "[", end = "]", close = true, newline = true },
    { start = "{", end = "}", close = true, newline = true },
    { start = "\"", end = "\"", close = true, newline = false, not_in = [
        "string",
    ] },
    { start = "'", end = "'", close = true, newline = false, not_in = [
        "string",
    ] },
    { start = "/*", end = " */", close = true, newline = true, not_in = [
        "string",
        "comment",
    ] },
    { start = "<*", end = " *>", close = true, newline = true, not_in = [
        "string",
        "comment",
    ] }
]
